/* eslint-disable */
// Generated by Wrangler by running `wrangler types src/cloudflare-env.d.ts --include-runtime false --strict-vars false` (hash: 4951c59784b8883af9f38b6d1875b2c4)
declare namespace Cloudflare {
	interface Env {
		DB: D1Database;
		HYPERDRIVE: Hyperdrive;
		POST_EVENTS: Queue;
		BETTER_AUTH_URL: string;
		ORPC_IN_PROCESS: string;
		ORPC_DB_DRIVER: string;
		AUTH_HASHER: Fetcher /* cloudflare-first-starter-auth-hasher */;
		OG_WORKER: Fetcher /* cloudflare-first-starter-worker-og */;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BETTER_AUTH_URL" | "ORPC_IN_PROCESS" | "ORPC_DB_DRIVER">> {}
}
