/* eslint-disable */
// Generated by Wrangler by running `wrangler types src/cloudflare-env.d.ts --include-runtime false --strict-vars false` (hash: ab89a68281c6d0a83439ac02b40cce78)
declare namespace Cloudflare {
	interface Env {
		DB: D1Database;
		BETTER_AUTH_URL: string;
		ORPC_IN_PROCESS: string;
		AUTH_HASHER: Fetcher /* cloudflare-first-starter-auth-hasher */;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BETTER_AUTH_URL" | "ORPC_IN_PROCESS">> {}
}
