/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false src/cloudflare-env.d.ts` (hash: a612470fb9ab9fd92883aef167664d46)
interface __BaseEnv_Env {
	DB: D1Database;
	HYPERDRIVE: Hyperdrive;
	POST_EVENTS: Queue;
	BETTER_AUTH_URL: string;
	ORPC_IN_PROCESS: string;
	ORPC_DB_DRIVER: string;
	AUTH_HASHER: Fetcher /* cloudflare-first-starter-auth-hasher */;
	OG_WORKER: Fetcher /* cloudflare-first-starter-worker-og */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BETTER_AUTH_URL" | "ORPC_IN_PROCESS" | "ORPC_DB_DRIVER">> {}
}
