/* eslint-disable */
// Generated by Wrangler by running `wrangler types src/cloudflare-env.d.ts --include-runtime false --strict-vars false` (hash: 30c2ed238fc864aed6759810418e1dd9)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env {
		DB: D1Database;
	}
}
interface Env extends Cloudflare.Env {}
