/* eslint-disable */
// Generated by Wrangler by running `wrangler types src/cloudflare-env.d.ts --include-runtime false --strict-vars false` (hash: 3aeb8404f49669a9e83833ac191dfacb)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env {
		OG_RATE_LIMIT: RateLimit;
	}
}
interface Env extends Cloudflare.Env {}
