/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false src/cloudflare-env.d.ts` (hash: 13f7d4848ea5fc80176d72dccd09dc70)
interface __BaseEnv_Env {
	OG_RATE_LIMIT: RateLimit;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
