/* eslint-disable */
// Generated by Wrangler by running `wrangler types src/cloudflare-env.d.ts --include-runtime false --strict-vars false` (hash: d71ce24a6eb43db5fe870f8f8fd02588)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "RateLimiterState";
	}
	interface Env {
		RATE_LIMITER: RateLimit;
		EDGE_GUARD_MODE: string;
		RATE_LIMITER_STATE: DurableObjectNamespace<import("./index").RateLimiterState>;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "EDGE_GUARD_MODE">> {}
}
