/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false src/cloudflare-env.d.ts` (hash: 7a1e0d865fc59717c3d06af4fe30bf19)
interface __BaseEnv_Env {
	RATE_LIMITER: RateLimit;
	EDGE_GUARD_MODE: string;
	RATE_LIMITER_STATE: DurableObjectNamespace<import("./index").RateLimiterState>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "RateLimiterState";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "EDGE_GUARD_MODE">> {}
}
